### ISSUE TITLE
フェッチャーアイテムの「範囲(range)」は「セル(cell)」の方がよいのでは?

### ISSUE THREAD

**Issue by atachibana** [naogify/wp-simple-spreadsheet-fetcher-for-google#30]
有用なプラグインです。ありがとうございます。
遊んでいてちょっととまどった点。アドバンスドフェッチャーは単一の値を取得しますが、「範囲」となっていて少し動作に戸惑いました。「セル」で良いのでは?
実際範囲を指定してもコードでは最初のセルのみを使用していますね。

build/get-value-query.php
```
$data = '<p class="wp2s2fg_fetcher-advanced_number">' . esc_html( $values[0][0] ) . '</p>';
```

**Comment by naogify** [comment]
アドバンスドフェッチャーで指定できるのは「セル」のみなので、修正します。
フィードバックありがとうございます!

**Comment by naogify** [comment]
バージョン0.3.7で修正しました!

**Comment by atachibana** [comment]
0.3.7 での修正を確認しました。
