### ISSUE TITLE
fetcher-advanced のフォントサイズが小さい

### ISSUE THREAD

**Issue by atachibana** [naogify/wp-simple-spreadsheet-fetcher-for-google#31]
該当箇所は小さなフォントで表示されますが、私の環境では小さすぎるかな。
<img width="599" alt="spread1" src="https://user-images.githubusercontent.com/8876600/71766783-3402be80-2f47-11ea-9c6c-c69ceff33720.png">

以下のスタイルが当たっているためですが、いっそ、削除してもいいのでは?

```
style.css 
.wp2s2fg_fetcher-advanced_price{
	font-size: 0.8rem;
}

.wp2s2fg_fetcher-advanced_number_container{
	font-size: 1.1rem;
}
```
<img width="607" alt="spread2" src="https://user-images.githubusercontent.com/8876600/71766790-4977e880-2f47-11ea-962e-0689a711e478.png">

ただ削除すると「/」とベースラインが合いませんがこれは `<p>` と `<span>` の違いから。
<img width="525" alt="spread3" src="https://user-images.githubusercontent.com/8876600/71766802-54327d80-2f47-11ea-92c8-53eef991d0f1.png">
`<span>` で統一すれば解決する?

**Comment by naogify** [comment]
バージョン0.3.7で修正しました!

**Comment by naogify** [comment]
フィードバックありがとうございます!

**Comment by atachibana** [comment]
0.3.7 での修正を確認しました。
