### ISSUE TITLE
CSRF

### ISSUE THREAD

**Issue by technote-space** [naogify/wp-simple-spreadsheet-fetcher-for-google#33]
## 概要
CSRFの脆弱性が存在します。

## 再現手順
POSTツールでログイン状態のクッキーとともに `/wp-admin/plugins.php?page=wsgsf_settings` に POST  
`api_key=任意の文字列`

## 期待する動作
無関係のページ等から更新されないこと

## スクリーンショット
![202001052349](https://user-images.githubusercontent.com/39912269/71781788-151f2d80-3016-11ea-831a-e12653717e0d.png)
![202001052350](https://user-images.githubusercontent.com/39912269/71781789-151f2d80-3016-11ea-9c47-a5f425be9cb1.png)

## 発生した環境
 - WP v5.3.2
 - Chrome v79.0.3945.88
 - WP Simple Spreadsheet Fetcher for Google v0.3.6

## 補足
add_submenu_page は権限のチェックはありますが送信元のチェック等はありません。  

form に token を埋め込み更新前にチェックするようにします。

https://github.com/naogify/wp-simple-spreadsheet-fetcher-for-google/blob/041cd62ff1065cdc139d4f5081f8a93513839532/wp-simple-spreadsheet-fetcher-for-google.php#L66-L70

https://github.com/naogify/wp-simple-spreadsheet-fetcher-for-google/blob/041cd62ff1065cdc139d4f5081f8a93513839532/wp-simple-spreadsheet-fetcher-for-google.php#L96-L100

もしくはSettings APIを使用します。
https://developer.wordpress.org/plugins/settings/settings-api/
https://nskw-style.com/2014/wordpress/settings-api.html

**Comment by naogify** [comment]
ご指摘ありがとうございます!
バージョン0.3.7で下のように修正しました。

https://github.com/naogify/wp-simple-spreadsheet-fetcher-for-google/blob/7f7405ea216615d7ee86b053af780e4d38147223/wp-simple-spreadsheet-fetcher-for-google.php#L66-L71

https://github.com/naogify/wp-simple-spreadsheet-fetcher-for-google/blob/7f7405ea216615d7ee86b053af780e4d38147223/wp-simple-spreadsheet-fetcher-for-google.php#L97-L101
